defmodule ExampleUsage do
  @moduledoc """
  Example usage of generated Protobuf modules.

  This module demonstrates how to use the Protobuf code generated by Bufrnix.
  """

  # Import the generated modules (these will exist after running bufrnix)
  # alias Proto.Example.V1.ExampleMessage
  # alias Proto.Example.V1.TimestampMessage
  # alias Proto.Example.V1.StatusMessage
  # alias Proto.Example.V1.ConfigMessage
  # alias Proto.Example.V1.NotificationMessage

  def demo do
    IO.puts("Bufrnix Elixir Example")
    IO.puts("======================")
    IO.puts("")
    IO.puts("This example demonstrates Protocol Buffer code generation for Elixir.")
    IO.puts("")
    IO.puts("To generate the protobuf code:")
    IO.puts("  1. Run: nix run")
    IO.puts("  2. The generated code will be in lib/proto/")
    IO.puts("")
    IO.puts("Once generated, you can use the modules like:")
    IO.puts("  message = %Proto.Example.V1.ExampleMessage{")
    IO.puts("    id: 1,")
    IO.puts("    name: \"Test User\",")
    IO.puts("    email: \"test@example.com\",")
    IO.puts("    tags: [\"elixir\", \"protobuf\"]")
    IO.puts("  }")
    IO.puts("")
    IO.puts("  # Encode to binary")
    IO.puts("  binary = Proto.Example.V1.ExampleMessage.encode(message)")
    IO.puts("")
    IO.puts("  # Decode from binary")
    IO.puts("  decoded = Proto.Example.V1.ExampleMessage.decode(binary)")
  end

  # Example functions that will work after code generation
  def create_example_message do
    # Uncomment after generation:
    # %Proto.Example.V1.ExampleMessage{
    #   id: 1,
    #   name: "Alice",
    #   email: "alice@example.com",
    #   tags: ["developer", "elixir"],
    #   description: "An example user",
    #   created_at: %Proto.Example.V1.TimestampMessage{
    #     seconds: System.system_time(:second),
    #     nanos: 0
    #   }
    # }
    {:ok, "Example message will be created after protobuf generation"}
  end

  def encode_decode_example do
    # Uncomment after generation:
    # message = create_example_message()
    # binary = Proto.Example.V1.ExampleMessage.encode(message)
    # decoded = Proto.Example.V1.ExampleMessage.decode(binary)
    # IO.inspect(decoded, label: "Decoded message")
    {:ok, "Encode/decode will work after protobuf generation"}
  end
end